### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by zzragida** [nhnent/socket.io-client-unity3d#1]
all samples not working because json parse exception.

**here is call stack**
ArgumentException: JSON parse error: The document root must not follow by other values.
UnityEngine.JsonUtility.FromJson[PollingUrlAnswer] (System.String json) (at C:/buildslave/unity/build/artifacts/generated/common/modules/JSONSerialize/JsonUtilityBindings.gen.cs:25)
socket.io.SocketInitializer+<InitCore>c__Iterator0.MoveNext () (at Assets/Plugins/socket.io/SocketInitializer.cs:169)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
![image](https://user-images.githubusercontent.com/4442732/27016228-973db616-4f58-11e7-9301-7a8d2b88f52c.png)

**maybe json format changed**
![socketio-unity-jsoninitializer-bug](https://user-images.githubusercontent.com/4442732/27016215-5cf96df6-4f58-11e7-9a80-7540b2f6693f.png)

**Comment by zzragida** [comment]
but python socket.io is correct working
maybe node.js server sample or library bug?
![image](https://user-images.githubusercontent.com/4442732/27016782-13221bf0-4f5e-11e7-8f81-30fe496e54b5.png)

**Comment by ppz0th** [comment]
I'll try and check it ASAP~

**Comment by zzragida** [comment]
tested on Unity 5.6.1

By the way, my python socket.io sample not working completely 
on unity connect callback not called.

socket.On("connect", () => {
   Debug.Log("Hello, socket.io~"); // not called
});

**Comment by ppz0th** [comment]
Hello~
 Recently, socket.io upgraded to v2.0.2 and it's not working on 'socket.io-client-unity3d'. 'socket.io-client-unity3d' only supports upto v1.7.4. So if you're working on Node.js, plz downgrade socket.io v1.7.4. You can do that by 'npm install socket.io@1.7.4'

 We're make an issue  related to v.2.0.2 compatibility and solve this ASAP~

**Comment by zzragida** [comment]
@ppz0th 
Confirm this issue i solve it.
Thank you for comment.

**Comment by smallmiro** [comment]
Relative issue #2 `Support socket.io v2.0.2`. Closed this issue
