### ISSUE TITLE
Decoder.cs throw error

### ISSUE THREAD

**Issue by gzlock** [nhnent/socket.io-client-unity3d#3]
When received message: "40/chat,", it throws the error:
```
IndexOutOfRangeException: Array index is out of range.
socket.io.Decoder.Decode (System.String data) (at Assets/Socket/socket.io/Decoder.cs:45)
```

**Comment by ppz0th** [comment]
Hello~ Chat demo is not working. It's my mistake to add Chat.cs and Chat.unity file in here. It'll be deleted soon.

**Comment by ppz0th** [comment]
@gzlock 
Chat sample code has been removed at v1.1.1
