### ISSUE TITLE
Download link in wiki is returnig 404

### ISSUE THREAD

**Issue by miladganjali** [nhnent/socket.io-client-unity3d#32]
Hello, Download link in the wiki in this [address](https://github.com/nhnent/socket.io-client-unity3d/wiki) return 404 page of GitHub. 

Download link : https://github.com/nhnent/socket.io-client-unity3d/releases/download/v1.1.1/Socket.IO-Client.unitypackage

**Comment by smallmiro** [comment]
I'm sorry. I changed download link. Could you check wiki?
And another download site is https://github.com/nhnent/socket.io-client-unity3d/releases.

Thank you.
