### ISSUE TITLE
SSL CertificateHandler in Socket for https connect

### ISSUE THREAD

**Issue by shmhlove** [nhnent/socket.io-client-unity3d#36]
Please check and apply the modification details of this code.

[commit Link](https://github.com/shmhlove/Asgardium_Client/commit/dfb4efc476c0d3b651fdc74a4cfd9c5017da1b00)

**Comment by smallmiro** [comment]
Thank's your contribution.
Could you write  Pull request of your code in our repository? And then can check your code.
Please move you're code to our repository, and write Pull request

**Comment by shmhlove** [comment]
Sorry,,

remote: Permission to nhnent/socket.io-client-unity3d.git denied to shmhlove.
fatal: unable to access 'https://github.com/nhnent/socket.io-client-unity3d.git/': The requested URL returned error: 403

**Comment by shmhlove** [comment]
> Thank's your contribution.
> Could you write Pull request of your code in our repository? And then can check your code.
> Please move you're code to our repository, and write Pull request

Sorry,,

remote: Permission to nhnent/socket.io-client-unity3d.git denied to shmhlove.
fatal: unable to access 'https://github.com/nhnent/socket.io-client-unity3d.git/': The requested URL returned error: 403

**Comment by lyzedev01** [comment]
@shmhlove 
Please read the contribution guide, Document link is https://github.com/nhnent/socket.io-client-unity3d/blob/master/CONTRIBUTING.md

**Comment by smallmiro** [comment]
Please read the contribution guide. A Document's link is https://github.com/nhnent/socket.io-client-unity3d/blob/master/CONTRIBUTING.md

**Comment by dheerajappm** [comment]
Hey @shmhlove  can you please tell me how to use the function 

   public static Socket Connect(string url, CertificateHandler certificateHandler) {
            var socket = new GameObject(string.Format("socket.io - {0}", url)).AddComponent<Socket>();
            socket.transform.SetParent(SocketManager.Instance.transform, false);
            socket.Url = new Uri(url);
            socket.certificateHandler = certificateHandler;

            SocketManager.Instance.Connect(socket);
            return socket;
        }
