### ISSUE TITLE
Get Json Error

### ISSUE THREAD

**Issue by farzadi** [nhnent/socket.io-client-unity3d#9]
I have an error like this 

ArgumentException: JSON parse error: The document root must not follow by other values.
UnityEngine.JsonUtility.FromJson[PollingUrlAnswer] (System.String json) (at C:/buildslave/unity/build/artifacts/generated/common/modules/JSONSerialize/JsonUtilityBindings.gen.cs:25)
socket.io.SocketInitializer+<InitCore>c__Iterator0.MoveNext () (at Assets/Assets/Plugins/socket.io/SocketInitializer.cs:169)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by gzlock** [comment]
Show your json string to help find the problem

**Comment by smallmiro** [comment]
@gzlock Thanks for you comment.
@farzadi If you used socket.io v2.x server, look at #1 'JSON parse error'  issus. Our library is not yet supported socket.io v2.0

**Comment by farzadi** [comment]
What is the solution? 
Should we switch to the previous version(e.g socket.io v1.7)?

**Comment by smallmiro** [comment]
Yes! You change previous version( socket.io v1.x). Probably 1.7 would be possible.
